name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  TF_VAR_access_key: ${{ secrets.access_key }}
  TF_VAR_secret_key: ${{ secrets.secret_key }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          echo "${{ secrets.public_key }}" > id_rsa.pub
          echo "${{ secrets.private_key }}" > id_rsa
          chmod 600 id_rsa

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply --auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy --auto-approve
          else
            echo "Invalid action: ${{ github.event.inputs.action }}"
            exit 1
          fi
